"""empty message

Revision ID: 4f7c48320b0f
Revises:
Create Date: 2020-02-09 13:21:51.162744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7c48320b0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcards',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('front', sa.Text(), nullable=True),
                    sa.Column('back', sa.Text(), nullable=True),
                    sa.Column('user_id', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.phone_number'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('phone_number', sa.Text(), nullable=False),
                    sa.Column('current_review_id', sa.Integer(), nullable=True),
                    sa.Column('creating_flashcards', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['current_review_id'], ['flashcards.id'], ),
                    sa.PrimaryKeyConstraint('phone_number')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('flashcards')
    # ### end Alembic commands ###
